<?php
// $Id:$

function pre($txt) {
  echo '<pre>';
  print_r($txt);
  echo '</pre>';
}

function newsletter_theme() {
  return array(
    'newsletter_list_form' => array(
      'arguments' => array('form' => NULL),
    ),
  );
}

function newsletter_menu() {
    $items['newsletter'] = array(
        'title' => t('Manage campaings'),
        'page callback' => 'drupal_get_form',
        //'access callback' => 'user_access',
        'access arguments' => array('admin newsletter'),
        'page arguments' => array('newsletter_list_form'),
        'file' => 'newsletter.admin.inc',
    );

    $items['newsletter/manage'] = array(
        'title' => t('Newsletters'),
        'type' => MENU_DEFAULT_LOCAL_TASK,
        'weight' => 1,
    );

    $items['newsletter/manage/list'] = array(
        'title' => t('List'),
        'type' => MENU_DEFAULT_LOCAL_TASK,
        'weight' => 1,
    );

    $items['newsletter/manage/add'] = array(
        'title' => t('Add newsletter'),
        'page callback' => 'node_add',
        'access callback' => 'user_access',
        'access arguments' => array('admin newsletter'),
        'page arguments' => array('newsletter'),
        'file' => 'node.pages.inc',
        'file path' => drupal_get_path('module', 'node'),
        'type' => MENU_LOCAL_TASK,
        'weight' => 2,
    );
    
    return $items;
}

function newsletter_node_info() {
    return array(
        'newsletter' => array(
            'name' => t('Newsletter'),
            'base' => 'newsletter',
            'description' => t('Newsletter module'),
            //'has_title' => TRUE,
            //'title_label' => t('Title'),
            //'help' => t('Enter the job title, job description, and the name of the company that posted the job'),
            //'has_body' => TRUE,
            //'body_label' => t('Body'),
            //'locked' => TRUE
        ),
    );
}

function newsletter_form($node, $form_state) {
  return node_content_form($node, $form_state);
}


/*
function newsletter_form($node){
    $type = node_type_get_type('type', $node);
    $form['title'] = array(
        '#type' => 'textfield',
        '#title' => check_plain($type->title_label),
        '#required' => TRUE,
        '#default_value' => $node->title,
        '#weight' => -5,
        '#maxlength' => 255,
    );

    $form['body_filter']['body'] = array(
        '#type' => 'textarea',
        '#title' => check_plain($type->body_label),
        '#default_value' => $node->body,
        '#rows' => 15,
        '#required' => TRUE,
    );

    //$form['body_filter']['filter'] = filter_form($node->format);
    return $form;
}
*/


