<?php
// $Id:$

function pre($txt) {
  echo '<pre>';
  print_r($txt);
  echo '</pre>';
}
function newsletter_perm() {
    return array(
        'admin newsletter', 
        'create newsletter', 
        'edit own newsletter', 
        'edit any newsletter', 
        'delete own newsletter', 
        'delete any newsletter'
      );
}
function newsletter_theme() {
  return array(
    'newsletter_list_search_form' => array(
      'arguments' => array('elements' => NULL),
      'file' => 'newsletter.admin.inc',
      'render element' => 'search',
    ),
  );
}
function newsletter_menu() {
    $items['newsletter'] = array(
        'title' => t('Manage campaings'),
        'page callback' => 'drupal_get_form',
        'access callback' => 'user_access',
        'access arguments' => array('admin newsletter'),
        'page arguments' => array('newsletter_list_form'),
        'file' => 'newsletter.admin.inc',
    );
    $items['newsletter/manage'] = array(
        'title' => t('Newsletters'),
        'type' => MENU_DEFAULT_LOCAL_TASK,
        'weight' => 1,
    );
    $items['newsletter/manage/list'] = array(
        'title' => t('List'),
        'type' => MENU_DEFAULT_LOCAL_TASK,
        'weight' => 1,
    );
    $items['newsletter/manage/add'] = array(
        'title' => t('Add newsletter'),
        'page callback' => 'node_add',
        'access callback' => 'user_access',
        'access arguments' => array('admin newsletter'),
        'page arguments' => array('newsletter'),
        'file' => 'node.pages.inc',
        'file path' => drupal_get_path('module', 'node'),
        'type' => MENU_LOCAL_TASK,
        'weight' => 2,
    );
    $items['newsletter/users'] = array(
        'title' => t('Users'),
        'page callback' => 'drupal_get_form',
        'access callback' => 'user_access',
        'access arguments' => array('admin newsletter'),
        'page arguments' => array('newsletter_list_user_form'),
        'file' => 'newsletter.admin.inc',
        'type' => MENU_LOCAL_TASK,
        'weight' => 2,
    );
    $items['newsletter/users/list'] = array(
        'title' => t('List'),
        'type' => MENU_DEFAULT_LOCAL_TASK,
        'weight' => 1,
    );
    $items['newsletter/users/add'] = array(
        'title' => t('Add'),
        'page callback' => 'node_add',
        'access arguments' => array('admin newsletter'),
        'type' => MENU_LOCAL_TASK,
        'weight' => 2,
    );
    $items['newsletter/manage/edit/%node'] = array(
        'title' => t('Edit newsletter'),
        'page callback' => 'node_page_edit',
        'access callback' => 'user_access',
        'access arguments' => array('admin newsletter'),
        'page arguments' => array(3),
        'file' => 'node.pages.inc',
        'file path' => drupal_get_path('module', 'node'),
        'type' => MENU_LOCAL_TASK,
        'weight' => 3,
    );
    $items['newsletter/template/%'] = array(
        'page callback' => 'newsletter_rpeview',
        'page arguments' => array(2),
        'access callback' => TRUE,
        'file' => 'newsletter.admin.inc',
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function newsletter_node_info() {
    return array(
        'newsletter' => array(
            'name' => t('Newsletter'),
            'base' => 'newsletter',
            'description' => t('Newsletter module'),
            //'has_title' => TRUE,
            //'title_label' => t('Title'),
            //'help' => t('Enter the job title, job description, and the name of the company that posted the job'),
            //'has_body' => TRUE,
            //'body_label' => t('Body'),
            //'locked' => TRUE
        ),
    );
}

function newsletter_access($op, $node, $account) {
    $is_author = $account->uid == $node->uid;
    switch ($op) {
        case 'create':
            return user_access('create newsletter', $account);
        case 'update':
            return user_access('edit own newsletter', $account) && $is_author || user_access('edit any newsletter', $account);
        case 'delete':
            return user_access('delete own newsletter', $account) && $is_author || user_access('delete any newsletter', $account);
    }
}

function newsletter_form($node, $form_state) {
  return node_content_form($node, $form_state);
}

function newsletter_form_alter(&$form, &$form_state, $form_id) {
    if($form_id == 'newsletter_node_form') {
        $form['buttons']['preview']['#access'] = FALSE;
        $form['buttons']['delete']['#access'] = FALSE;
        $form['comment_settings']['comment']['#default_value'] = 0;
        $form['options']['promote']['#default_value'] = 0;
        $form['comment_settings']['#access'] = FALSE;
        $form['options']['#access'] = FALSE;
        $form['author']['#access'] = FALSE;
        $form['revision_information']['#access'] = FALSE;
        $form['menu']['#access'] = FALSE;
        $form['path']['#access'] = FALSE;
        $form['#redirect'] = 'newsletter';
    }
}
